### ISSUE TITLE
GraalVM 19.3.0 with JDK 8 and JDK 11

### ISSUE THREAD

**Issue by wololock** [sdkman/sdkman-db-migrations#181]
The GraalVM team just released [GraalVM CE 19.3.0](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-19.3.0). Things are getting more complicated - it now delivers two different versions, one based on JDK 8, and one based on JDK 11. How should we name the tag to support both versions? I was thinking about something like:

* `19.3.0-jdk8-grl`
* `19.3.0-jdk11-grl`

But the second one is 16 characters long, and as far as I remember we are limited to 15 :( 

Do you have any ideas how to solve this problem?

**Comment by marc0der** [comment]
The extra dash will break the algorithms so we probably need to make that a `.`.
How about we shorten the `jdk` portion and make it a `j` or something like that? So, `19.3.0.j8-grl` and `19.3.0.j11-grl`? Only problem is it might cause some confusion with the j9 variant of AdoptOpenJDK.

**Comment by wololock** [comment]
Hmm, `j8` and `j11` do not sound very intuitive. I think most of us used to labels like `jdk8`, `jdk11`. And yes, it might be confusing when taking `j9`JDK into account :/ Maybe `19.3.0jdk11-grl` would do the trick? It misses separation between numeric version and JDK variant, and might not be the most convenient when writing, but I don't have any better idea atm.

**Comment by rsvoboda** [comment]
Don't forget there was https://github.com/oracle/graal/releases/tag/vm-19.2.0.1 release
Something similar can happen to 19.3.0 or to any future release

I think the only way is to get rid of that 15 characters limit (although I don't know the details why it is there ...)

**Comment by wololock** [comment]
That is the good point, @rsvoboda. The 15 character limit was reached for the first time one year ago, when we worked on adding GraalVM 1.0.0-RC10. Marco explained this limitation here - https://github.com/sdkman/sdkman-db-migrations/pull/50 

I would definitely prefer using more than 15 characters, but only @marc0der knows possible side effects of such change.

**Comment by marc0der** [comment]
The main reason for the 15 character limitation is due to the list view truncating on candidates _other_ than Java. In those cases, it leaves the user blind because they can't see what is available to install, which is very bad ux and imo not acceptable. This limitation has never been a problem on non-java candidates, until we introduced java with vendor suffix in the version which pushes it beyond 15 chars.

The right solution here is to complete the work I started in separating `vendor` from `version` in the domain, which will give us lots of headroom in the version string. Java versions are now all published with a separate vendor attribute in the db already. I just need to do the work to surface this through the serverside to the CLI.

The plan is that you can then install java with the following pattern: `sdk install java <version> <vendor>`. For example:
```
$ sdk install java 19.3.0.jdk8 graal
```

I suggest a short term solution of doing what is required to get graalvm 19.3.0 out by using some version extension like `19.3.0.r11-grl` (pick a letter).
While this gets us across the line for a few days or so, I will go and make work of completing the vendor separation that I mentioned earlier. When this rolls out, I'll rename all java versions without their suffix so that the above syntax can work.

Any thoughts?

**Comment by marc0der** [comment]
@rsvoboda the problem we are faced with here is not really how the version is formed, but more in the uniformity between vendor versions. Java is unique in that many JDK vendors have their own version scheme, which is a real pain.

This is why I introduced the current scheme based on the new standard [Java versioning scheme](https://openjdk.java.net/jeps/322). Of course, we are bending this to accommodate AdoptOpenJDK j9/hs releases and JDK ea releases already, but the ordering is still working correctly despite these outliers. Hope this makes sense!

**Comment by ilopmar** [comment]
I was commenting this yesterday in the slack channel. One of my suggestions were `19.3.0-1.8-grl` and `19.3.0-1.11-grl` that may work for now but that won't work if/when they release  `19.3.0.1`. 

I like @wololock's suggestion about using `19.3.0-jdk8-grl` and `19.3.0-jdk11-grl` but at this moment is not possible until @marc0der does the changes to separate the vendor because we reach the 15 characters limit.

I think we should release the versions soon and then let Marco work on the changes. He will finish them before the GraalVM team releases an hypothetical 19.3.0.1 if that even happens...

**Comment by wololock** [comment]
Extracting vendor from the version sounds like the best option. I agree that we should release GraalVM 19.3.0 with some temporary version identifier that can be fixed when @marc0der finishes vendors feature. :+1: It want harm anyone if it uses `19.3.0.r11-grl` and `19.3.0.r8-grl` for a few days :sunglasses:

**Comment by ilopmar** [comment]
Agreed! @marc0der if you are ok with @wololock's proposal we can send the PR to release the new versions.

**Comment by marc0der** [comment]
That's perfect, let's do it!

**Comment by wololock** [comment]
Pull request ready to review - https://github.com/sdkman/sdkman-db-migrations/pull/182
